GET http://localhost:8000/api/products/

###
POST http://localhost:8000/api/products/
Content-Type: application/json

{
    "name": "Product 4",
    "price": 400,
    "stock": 40 
}

###

PATCH http://localhost:8000/api/products/1/
Content-Type: application/json

{
    "stock": 10
}

###
GET http://localhost:8000/api/sales/

###
POST http://localhost:8000/api/sales/
Content-Type: application/json

{
    "items_data": [
        {
            "product": 2,
            "quantity": 3
        }
    ]   
}

